{% set name = "molbloom" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/whitead/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4fb187a612f8da59473ac78b893d94fb6c1c6c2daf4027a8228e8b9dc00e7b13

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}

  host:
    - python
    - pip
    - cython
  run:
    - python
    - rdkit
    - importlib_resources

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - molbloom

about:
  home: https://whitead.github.io/molbloom/
  summary: Purchaseable SMILES filter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmacdope
    - whitead
    - ijpulidos
