{% set name = "molbloom" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/whitead/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b9bce6e0c008ff234be03defeebc72703d1381bf8a49dc62449d9fc8bc384c21

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}

  host:
    - python
    - pip
    - cython
    - setuptools
  run:
    - python
    - rdkit
    - importlib_resources
    - setuptools

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - molbloom

about:
  home: https://whitead.github.io/molbloom/
  summary: Purchaseable SMILES filter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmacdope
    - whitead
    - ijpulidos
