{% set name = "molbloom" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/whitead/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d107df25663f96964b771ecc08ca01dc4fa0cc8ef0706a6eb14715522936b594

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}

  host:
    - python
    - pip
    - cython
  run:
    - python
    - rdkit
    - importlib_resources

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - molbloom

about:
  home: https://whitead.github.io/molbloom/
  summary: Purchaseable SMILES filter
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmacdope
    - whitead
    - ijpulidos
